# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.20.00, with svd2pac 0.5.0 on Mon, 14 Apr 2025 11:21:40 +0000

[package]
name = "ra6t3-pac"
version = "0.1.0"
edition = "2024"
description = "Peripheral Access Crate (PAC) for R7FAA6T3."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra6t3", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra6t3-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
rmpu = []
tzf = []
sram = []
bus = []
dmac0 = []
dmac1 = ["dmac0"]
dmac2 = ["dmac0"]
dmac3 = ["dmac0"]
dmac4 = ["dmac0"]
dmac5 = ["dmac0"]
dmac6 = ["dmac0"]
dmac7 = ["dmac0"]
dma = []
dtc = []
icu = []
cache = []
cpscu = []
dbg = []
fcache = []
sysc = []
tfu = []
port0 = []
port1 = []
port2 = ["port1"]
port3 = ["port1"]
port4 = ["port1"]
port5 = ["port0"]
port8 = ["port0"]
pfs = []
elc = []
rtc = []
iwdt = []
wdt = []
cac = []
mstp = []
poeg = []
usbfs = []
canfd_b = []
pscu = []
agtw0 = []
agtw1 = ["agtw0"]
tsn = []
acmphs0 = []
acmphs1 = ["acmphs0"]
acmphs2 = ["acmphs0"]
crc = []
doc = []
sci0 = []
sci9 = ["sci0"]
spi0 = []
spi1 = ["spi0"]
i3c = []
eccmb = []
gpt16e0 = []
gpt16e1 = ["gpt16e0"]
gpt16e2 = ["gpt16e0"]
gpt16e3 = ["gpt16e0"]
gpt16e4 = ["gpt16e0"]
gpt16e5 = ["gpt16e0"]
gpt_ops = []
adc120 = []
dac12 = []
tsd = []
flad = []
faci = []

all = [
    "rmpu",
    "tzf",
    "sram",
    "bus",
    "dmac0",
    "dmac1",
    "dmac2",
    "dmac3",
    "dmac4",
    "dmac5",
    "dmac6",
    "dmac7",
    "dma",
    "dtc",
    "icu",
    "cache",
    "cpscu",
    "dbg",
    "fcache",
    "sysc",
    "tfu",
    "port0",
    "port1",
    "port2",
    "port3",
    "port4",
    "port5",
    "port8",
    "pfs",
    "elc",
    "rtc",
    "iwdt",
    "wdt",
    "cac",
    "mstp",
    "poeg",
    "usbfs",
    "canfd_b",
    "pscu",
    "agtw0",
    "agtw1",
    "tsn",
    "acmphs0",
    "acmphs1",
    "acmphs2",
    "crc",
    "doc",
    "sci0",
    "sci9",
    "spi0",
    "spi1",
    "i3c",
    "eccmb",
    "gpt16e0",
    "gpt16e1",
    "gpt16e2",
    "gpt16e3",
    "gpt16e4",
    "gpt16e5",
    "gpt_ops",
    "adc120",
    "dac12",
    "tsd",
    "flad",
    "faci",
]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all", "rt"]
