# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.2, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:20:32 +0000

[package]
name = "ra8m1-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA8M1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra8m1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra8m1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
rmpu = []
sram = []
bus = []
tzf = []
icu_common = []
cpscu = []
dmac0 = []
dmac1 = [ "dmac0" ]
dmac2 = [ "dmac0" ]
dmac3 = [ "dmac0" ]
dmac4 = [ "dmac0" ]
dmac5 = [ "dmac0" ]
dmac6 = [ "dmac0" ]
dmac7 = [ "dmac0" ]
dma = []
dtc = []
icu = []
cpu_ocd = []
cpu_dbg = []
fcache = []
sysc = []
tsd = []
flad = []
faci = []
elc = []
rtc = []
iwdt = []
cac = []
wdt = []
mstp = []
pscu = []
poeg = []
ulpt0 = []
ulpt1 = [ "ulpt0" ]
agt0 = []
agt1 = [ "agt0" ]
tsn = []
acmphs0 = []
acmphs1 = [ "acmphs0" ]
usbfs = []
sdhi0 = []
sdhi1 = [ "sdhi0" ]
ssie0 = []
ssie1 = [ "ssie0" ]
iic0 = []
iic0wu = []
iic1 = []
xspi = []
crc = []
doc = []
gpt320 = []
gpt321 = [ "gpt320" ]
gpt322 = [ "gpt320" ]
gpt323 = [ "gpt320" ]
gpt324 = [ "gpt320" ]
gpt325 = [ "gpt320" ]
gpt326 = [ "gpt320" ]
gpt327 = [ "gpt320" ]
gpt168 = [ "gpt320" ]
gpt169 = [ "gpt320" ]
gpt1610 = [ "gpt320" ]
gpt1611 = [ "gpt320" ]
gpt1612 = [ "gpt320" ]
gpt1613 = [ "gpt320" ]
gpt_ops = []
adc120 = []
adc121 = []
dac12 = []
glcdc = []
drw = []
dsilink = []
dphycnt = []
ceu = []
usbhs = []
edmac0 = []
etherc0 = []
sci0 = []
sci1 = [ "sci0" ]
sci2 = [ "sci0" ]
sci3 = [ "sci0" ]
sci4 = [ "sci0" ]
sci9 = [ "sci0" ]
spi0 = []
spi1 = [ "spi0" ]
i3c = []
eccmb0 = []
eccmb1 = [ "eccmb0" ]
canfd0 = []
canfd1 = [ "canfd0" ]
port0 = []
port1 = []
port2 = [ "port1" ]
port3 = [ "port1" ]
port4 = [ "port1" ]
port5 = [ "port0" ]
port6 = [ "port0" ]
port7 = [ "port0" ]
port8 = [ "port0" ]
port9 = [ "port0" ]
porta = [ "port0" ]
portb = [ "port0" ]
portc = [ "port0" ]
portd = [ "port0" ]
porte = [ "port0" ]
portf = [ "port0" ]
portg = [ "port0" ]
pfs = []
rmpu_ns = [ "rmpu" ]
sram_ns = [ "sram" ]
bus_ns = [ "bus" ]
tzf_ns = [ "tzf" ]
icu_common_ns = [ "icu_common" ]
cpscu_ns = [ "cpscu" ]
dmac0_ns = [ "dmac0" ]
dmac1_ns = [ "dmac0" ]
dmac2_ns = [ "dmac0" ]
dmac3_ns = [ "dmac0" ]
dmac4_ns = [ "dmac0" ]
dmac5_ns = [ "dmac0" ]
dmac6_ns = [ "dmac0" ]
dmac7_ns = [ "dmac0" ]
dma_ns = [ "dma" ]
dtc_ns = [ "dtc" ]
icu_ns = [ "icu" ]
cpu_ocd_ns = [ "cpu_ocd" ]
cpu_dbg_ns = [ "cpu_dbg" ]
fcache_ns = [ "fcache" ]
sysc_ns = [ "sysc" ]
tsd_ns = [ "tsd" ]
flad_ns = [ "flad" ]
faci_ns = [ "faci" ]
elc_ns = [ "elc" ]
rtc_ns = [ "rtc" ]
iwdt_ns = [ "iwdt" ]
cac_ns = [ "cac" ]
wdt_ns = [ "wdt" ]
mstp_ns = [ "mstp" ]
pscu_ns = [ "pscu" ]
poeg_ns = [ "poeg" ]
ulpt0_ns = [ "ulpt0" ]
ulpt1_ns = [ "ulpt0" ]
agt0_ns = [ "agt0" ]
agt1_ns = [ "agt0" ]
tsn_ns = [ "tsn" ]
acmphs0_ns = [ "acmphs0" ]
acmphs1_ns = [ "acmphs0" ]
usbfs_ns = [ "usbfs" ]
sdhi0_ns = [ "sdhi0" ]
sdhi1_ns = [ "sdhi0" ]
ssie0_ns = [ "ssie0" ]
ssie1_ns = [ "ssie0" ]
iic0_ns = [ "iic0" ]
iic0wu_ns = [ "iic0wu" ]
iic1_ns = [ "iic1" ]
xspi_ns = [ "xspi" ]
crc_ns = [ "crc" ]
doc_ns = [ "doc" ]
gpt320_ns = [ "gpt320" ]
gpt321_ns = [ "gpt320" ]
gpt322_ns = [ "gpt320" ]
gpt323_ns = [ "gpt320" ]
gpt324_ns = [ "gpt320" ]
gpt325_ns = [ "gpt320" ]
gpt326_ns = [ "gpt320" ]
gpt327_ns = [ "gpt320" ]
gpt168_ns = [ "gpt320" ]
gpt169_ns = [ "gpt320" ]
gpt1610_ns = [ "gpt320" ]
gpt1611_ns = [ "gpt320" ]
gpt1612_ns = [ "gpt320" ]
gpt1613_ns = [ "gpt320" ]
gpt_ops_ns = [ "gpt_ops" ]
adc120_ns = [ "adc120" ]
adc121_ns = [ "adc121" ]
dac12_ns = [ "dac12" ]
glcdc_ns = [ "glcdc" ]
drw_ns = [ "drw" ]
dsilink_ns = [ "dsilink" ]
dphycnt_ns = [ "dphycnt" ]
ceu_ns = [ "ceu" ]
usbhs_ns = [ "usbhs" ]
edmac0_ns = [ "edmac0" ]
etherc0_ns = [ "etherc0" ]
sci0_ns = [ "sci0" ]
sci1_ns = [ "sci0" ]
sci2_ns = [ "sci0" ]
sci3_ns = [ "sci0" ]
sci4_ns = [ "sci0" ]
sci9_ns = [ "sci0" ]
spi0_ns = [ "spi0" ]
spi1_ns = [ "spi0" ]
i3c_ns = [ "i3c" ]
eccmb0_ns = [ "eccmb0" ]
eccmb1_ns = [ "eccmb0" ]
canfd0_ns = [ "canfd0" ]
canfd1_ns = [ "canfd0" ]
port0_ns = [ "port0" ]
port1_ns = [ "port1" ]
port2_ns = [ "port1" ]
port3_ns = [ "port1" ]
port4_ns = [ "port1" ]
port5_ns = [ "port0" ]
port6_ns = [ "port0" ]
port7_ns = [ "port0" ]
port8_ns = [ "port0" ]
port9_ns = [ "port0" ]
porta_ns = [ "port0" ]
portb_ns = [ "port0" ]
portc_ns = [ "port0" ]
portd_ns = [ "port0" ]
porte_ns = [ "port0" ]
portf_ns = [ "port0" ]
portg_ns = [ "port0" ]
pfs_ns = [ "pfs" ]

all = ["rmpu" ,"sram" ,"bus" ,"tzf" ,"icu_common" ,"cpscu" ,"dmac0" ,"dmac1" ,"dmac2" ,"dmac3" ,"dmac4" ,"dmac5" ,"dmac6" ,"dmac7" ,"dma" ,"dtc" ,"icu" ,"cpu_ocd" ,"cpu_dbg" ,"fcache" ,"sysc" ,"tsd" ,"flad" ,"faci" ,"elc" ,"rtc" ,"iwdt" ,"cac" ,"wdt" ,"mstp" ,"pscu" ,"poeg" ,"ulpt0" ,"ulpt1" ,"agt0" ,"agt1" ,"tsn" ,"acmphs0" ,"acmphs1" ,"usbfs" ,"sdhi0" ,"sdhi1" ,"ssie0" ,"ssie1" ,"iic0" ,"iic0wu" ,"iic1" ,"xspi" ,"crc" ,"doc" ,"gpt320" ,"gpt321" ,"gpt322" ,"gpt323" ,"gpt324" ,"gpt325" ,"gpt326" ,"gpt327" ,"gpt168" ,"gpt169" ,"gpt1610" ,"gpt1611" ,"gpt1612" ,"gpt1613" ,"gpt_ops" ,"adc120" ,"adc121" ,"dac12" ,"glcdc" ,"drw" ,"dsilink" ,"dphycnt" ,"ceu" ,"usbhs" ,"edmac0" ,"etherc0" ,"sci0" ,"sci1" ,"sci2" ,"sci3" ,"sci4" ,"sci9" ,"spi0" ,"spi1" ,"i3c" ,"eccmb0" ,"eccmb1" ,"canfd0" ,"canfd1" ,"port0" ,"port1" ,"port2" ,"port3" ,"port4" ,"port5" ,"port6" ,"port7" ,"port8" ,"port9" ,"porta" ,"portb" ,"portc" ,"portd" ,"porte" ,"portf" ,"portg" ,"pfs" ,"rmpu_ns" ,"sram_ns" ,"bus_ns" ,"tzf_ns" ,"icu_common_ns" ,"cpscu_ns" ,"dmac0_ns" ,"dmac1_ns" ,"dmac2_ns" ,"dmac3_ns" ,"dmac4_ns" ,"dmac5_ns" ,"dmac6_ns" ,"dmac7_ns" ,"dma_ns" ,"dtc_ns" ,"icu_ns" ,"cpu_ocd_ns" ,"cpu_dbg_ns" ,"fcache_ns" ,"sysc_ns" ,"tsd_ns" ,"flad_ns" ,"faci_ns" ,"elc_ns" ,"rtc_ns" ,"iwdt_ns" ,"cac_ns" ,"wdt_ns" ,"mstp_ns" ,"pscu_ns" ,"poeg_ns" ,"ulpt0_ns" ,"ulpt1_ns" ,"agt0_ns" ,"agt1_ns" ,"tsn_ns" ,"acmphs0_ns" ,"acmphs1_ns" ,"usbfs_ns" ,"sdhi0_ns" ,"sdhi1_ns" ,"ssie0_ns" ,"ssie1_ns" ,"iic0_ns" ,"iic0wu_ns" ,"iic1_ns" ,"xspi_ns" ,"crc_ns" ,"doc_ns" ,"gpt320_ns" ,"gpt321_ns" ,"gpt322_ns" ,"gpt323_ns" ,"gpt324_ns" ,"gpt325_ns" ,"gpt326_ns" ,"gpt327_ns" ,"gpt168_ns" ,"gpt169_ns" ,"gpt1610_ns" ,"gpt1611_ns" ,"gpt1612_ns" ,"gpt1613_ns" ,"gpt_ops_ns" ,"adc120_ns" ,"adc121_ns" ,"dac12_ns" ,"glcdc_ns" ,"drw_ns" ,"dsilink_ns" ,"dphycnt_ns" ,"ceu_ns" ,"usbhs_ns" ,"edmac0_ns" ,"etherc0_ns" ,"sci0_ns" ,"sci1_ns" ,"sci2_ns" ,"sci3_ns" ,"sci4_ns" ,"sci9_ns" ,"spi0_ns" ,"spi1_ns" ,"i3c_ns" ,"eccmb0_ns" ,"eccmb1_ns" ,"canfd0_ns" ,"canfd1_ns" ,"port0_ns" ,"port1_ns" ,"port2_ns" ,"port3_ns" ,"port4_ns" ,"port5_ns" ,"port6_ns" ,"port7_ns" ,"port8_ns" ,"port9_ns" ,"porta_ns" ,"portb_ns" ,"portc_ns" ,"portd_ns" ,"porte_ns" ,"portf_ns" ,"portg_ns" ,"pfs_ns"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all","rt"]
