# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.50.00, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:15:16 +0000

[package]
name = "ra2l1-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA2L1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra2l1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra2l1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license-file = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
rmpu = []
sram = []
bus = []
dtc = []
icu = []
dbg = []
sysc = []
port0 = []
port1 = []
port2 = ["port1"]
port3 = ["port0"]
port4 = ["port0"]
port5 = ["port0"]
port6 = ["port0"]
port7 = ["port0"]
port8 = ["port0"]
pfs = []
elc = []
poeg = []
rtc = []
wdt = []
iwdt = []
cac = []
mstp = []
can0 = []
iic0 = []
iic0wu = []
iic1 = ["iic0"]
doc = []
adc120 = []
dac12 = []
sci0 = []
sci1 = []
sci2 = ["sci1"]
sci3 = ["sci1"]
sci9 = ["sci1"]
spi0 = []
spi1 = ["spi0"]
crc = []
gpt320 = []
gpt321 = ["gpt320"]
gpt322 = ["gpt320"]
gpt323 = ["gpt320"]
gpt164 = []
gpt165 = ["gpt164"]
gpt166 = ["gpt164"]
gpt167 = ["gpt164"]
gpt168 = ["gpt164"]
gpt169 = ["gpt164"]
gpt_ops = []
kint = []
ctsu = []
agt0 = []
agt1 = ["agt0"]
acmplp = []
flcn = []

all = [
    "rmpu",
    "sram",
    "bus",
    "dtc",
    "icu",
    "dbg",
    "sysc",
    "port0",
    "port1",
    "port2",
    "port3",
    "port4",
    "port5",
    "port6",
    "port7",
    "port8",
    "pfs",
    "elc",
    "poeg",
    "rtc",
    "wdt",
    "iwdt",
    "cac",
    "mstp",
    "can0",
    "iic0",
    "iic0wu",
    "iic1",
    "doc",
    "adc120",
    "dac12",
    "sci0",
    "sci1",
    "sci2",
    "sci3",
    "sci9",
    "spi0",
    "spi1",
    "crc",
    "gpt320",
    "gpt321",
    "gpt322",
    "gpt323",
    "gpt164",
    "gpt165",
    "gpt166",
    "gpt167",
    "gpt168",
    "gpt169",
    "gpt_ops",
    "kint",
    "ctsu",
    "agt0",
    "agt1",
    "acmplp",
    "flcn",
]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all", "rt"]
