# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.0, with svd2pac 0.5.0 on Mon, 14 Apr 2025 11:21:11 +0000

[package]
name = "ra6t1-pac"
version = "0.1.0"
edition = "2024"
description = "Peripheral Access Crate (PAC) for R7FAA6T1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra6t1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra6t1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license-file = "LICENSE.txt"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
dac12 = []
acmphs0 = []
acmphs1 = []
acmphs2 = ["acmphs1"]
acmphs3 = ["acmphs1"]
acmphs4 = ["acmphs1"]
acmphs5 = ["acmphs1"]
tsn = []
crc = []
elc = []
cac = []
doc = []
iwdt = []
kint = []
wdt = []
can0 = []
can1 = ["can0"]
irda = []
spi0 = []
spi1 = ["spi0"]
srcram = []
src = []
dbg = []
dmac0 = []
dmac1 = ["dmac0"]
dmac2 = ["dmac0"]
dmac3 = ["dmac0"]
dmac4 = ["dmac0"]
dmac5 = ["dmac0"]
dmac6 = ["dmac0"]
dmac7 = ["dmac0"]
dma = []
dtc = []
mmf = []
sram = []
fcache = []
system = []
mstp = []
agt0 = []
agt1 = ["agt0"]
gpt_ops = []
gpt32eh0 = []
gpt32eh1 = ["gpt32eh0"]
gpt32eh2 = ["gpt32eh0"]
gpt32eh3 = ["gpt32eh0"]
gpt32e4 = ["gpt32eh0"]
gpt32e5 = ["gpt32eh0"]
gpt32e6 = ["gpt32eh0"]
gpt32e7 = ["gpt32eh0"]
poeg = []
gpt_odc = []
bus = []
icu = []
port0 = []
port1 = []
port2 = ["port1"]
port3 = ["port1"]
port4 = ["port1"]
port5 = ["port0"]
port6 = ["port0"]
port7 = ["port0"]
pfs = []
pmisc = []
iic0 = []
iic1 = []
sci0 = []
sci1 = ["sci0"]
sci2 = ["sci0"]
sci3 = ["sci0"]
sci4 = ["sci0"]
sci8 = ["sci0"]
sci9 = ["sci0"]
gpt328 = []
gpt329 = ["gpt328"]
gpt3210 = ["gpt328"]
gpt3211 = ["gpt328"]
gpt3212 = ["gpt328"]
adc120 = []
adc121 = []
mmpu = []
smpu = []
spmon = []
tsd = []

all = [
    "dac12",
    "acmphs0",
    "acmphs1",
    "acmphs2",
    "acmphs3",
    "acmphs4",
    "acmphs5",
    "tsn",
    "crc",
    "elc",
    "cac",
    "doc",
    "iwdt",
    "kint",
    "wdt",
    "can0",
    "can1",
    "irda",
    "spi0",
    "spi1",
    "srcram",
    "src",
    "dbg",
    "dmac0",
    "dmac1",
    "dmac2",
    "dmac3",
    "dmac4",
    "dmac5",
    "dmac6",
    "dmac7",
    "dma",
    "dtc",
    "mmf",
    "sram",
    "fcache",
    "system",
    "mstp",
    "agt0",
    "agt1",
    "gpt_ops",
    "gpt32eh0",
    "gpt32eh1",
    "gpt32eh2",
    "gpt32eh3",
    "gpt32e4",
    "gpt32e5",
    "gpt32e6",
    "gpt32e7",
    "poeg",
    "gpt_odc",
    "bus",
    "icu",
    "port0",
    "port1",
    "port2",
    "port3",
    "port4",
    "port5",
    "port6",
    "port7",
    "pfs",
    "pmisc",
    "iic0",
    "iic1",
    "sci0",
    "sci1",
    "sci2",
    "sci3",
    "sci4",
    "sci8",
    "sci9",
    "gpt328",
    "gpt329",
    "gpt3210",
    "gpt3211",
    "gpt3212",
    "adc120",
    "adc121",
    "mmpu",
    "smpu",
    "spmon",
    "tsd",
]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all", "rt"]
